"""Can an aerial hit a grounded opponent while rising, or only while falling? Jump height and an aerial's vertical hitbox
geometry decide it together, so neither is comparable alone (a low short hop with a low-reaching fair is an approach
tool; a high one is a retreat or landing tool; Falco's low short hop and huge full hop are his identity).
For each fighter's aerials, from a short hop and a full hop (no drift, no fast fall), input on airborne frame k:
  first    the earliest k that connects with the target (the move's hit meeting the target's body height)
  rising   how many input frames connect while he is still going up (before the apex); 0 = falling-only
  cover    how many input frames connect at all during the jump
  dist     the farthest distance between the two fighters' positions at which that hit connects
Targets are measured bodies (datkit movedata: Wait1 and SquatWait hurtboxes): standing and crouching Fox, standing Marth,
standing Jigglypuff.
    .venv/bin/python projects/geno/director/labs/aerial_profile.py ~/games/melee/work/movedata [OUT.md]
"""
import json, math, os, sys

sys.path.insert(0, os.path.dirname(__file__))
from cast_moves import CSV_NAME, NAMES, WATCH, attrs, GENO_ATTRS

AERIALS = ['nair', 'fair', 'bair', 'uair', 'dair']
TARGETS = [('Fx', 'stand'), ('Fx', 'crouch'), ('Ms', 'stand'), ('Pr', 'stand')]


def load(d):
    moves, bodies = {}, {}
    for f in os.listdir(d):
        code = f[:-6]
        if not f.endswith('.jsonl') or code not in NAMES: continue
        for l in open(os.path.join(d, f)):
            if not l.strip(): continue
            o = json.loads(l)
            if 'body' in o: bodies.setdefault(code, {})[o['body']] = o
            else: moves.setdefault(code, {})[o['move']] = o
    return moves, bodies


def traj(v0, g, term, n=120):
    y, vy, ys = 0.0, v0, []
    for _ in range(n):
        y += vy; vy -= g
        if vy < -term: vy = -term
        ys.append(max(y, 0.0))
        if y <= 0 and len(ys) > 1: break
    apex = max(range(len(ys)), key=lambda i: ys[i])
    return ys, apex


def reach_at(sphere_y, sphere_z, r, top):
    """How far forward a hit sphere touches a body of height `top` standing on the floor, or None."""
    if sphere_y - r > top or sphere_y + r < 0: return None
    dy = max(0.0, sphere_y - top, -sphere_y)
    return sphere_z + math.sqrt(max(0.0, r * r - dy * dy))


def profile(o, ys, apex, top, front, back=False):
    first, rising, cover, best = None, 0, 0, None
    for k in range(1, len(ys)):
        hit = None
        for f, spheres in o.get('geo', []):
            t = k + f - 1
            if t >= len(ys): break                             # landed first (landing cancels the aerial)
            for cy, cz, r in spheres:
                z = -cz if back else cz
                d = reach_at(ys[t] + cy, z, r, top)
                if d is not None:
                    dist = d + front
                    if hit is None or dist > hit[1]: hit = (t, dist)
            if hit: break
        if hit:
            cover += 1
            if first is None: first = k
            if hit[0] < apex: rising += 1
            best = max(best or 0, hit[1])
    return first, rising, cover, best


HEADER = """# Aerial approach profiles (measured)

Can an aerial hit a grounded opponent while rising, or only while falling? From a short hop (SH) and a full hop (FH),
no drift, no fast fall, the aerial input on airborne frame k. Cells: `k` the earliest input that connects, `r` how many
inputs connect while still rising, `c` how many connect at all, `u` the farthest distance between the fighters' positions
at which it connects. Targets are measured bodies (Fox standing 15.6 tall, crouching 10.8). Generated by
`director/labs/aerial_profile.py` from `datkit movedata`.
"""


def main(d, out=None):
    moves, bodies = load(d)
    lines = [HEADER]
    at = attrs()
    rows = {}
    for code in list(WATCH) + ['Ge']:
        r = {k: float(v) for k, v in (at[CSV_NAME[code]].items() if code != 'Ge' else GENO_ATTRS.items()) if k != 'fighter'}
        g, term = r['Gravity'], r['TerminalVelocity']
        jumps = {'SH': traj(r['MaximumShorthopVerticalVelocity'], g, term), 'FH': traj(r['InitialVerticalJumpVelocity'], g, term)}
        rows[code] = (jumps, r)
    lines.append('| fighter | jump (apex frame, height) | ' + ' | '.join(f'{a} vs {NAMES[t]} {p}' for a in AERIALS for t, p in TARGETS[:2]) + ' |')
    lines.append('|---|---|' + '---|' * (len(AERIALS) * 2))
    for code, (jumps, r) in rows.items():
        for jn, (ys, apex) in jumps.items():
            cells = []
            for a in AERIALS:
                o = moves.get(code, {}).get(a)
                for tc, tp in TARGETS[:2]:
                    b = bodies.get(tc, {}).get(tp)
                    if not o or not b or 'geo' not in o: cells.append(''); continue
                    first, rising, cover, best = profile(o, ys, apex, b['top'], b['front'], back=(a == 'bair'))
                    cells.append('-' if first is None else f'k{first} r{rising} c{cover} {best:.0f}u')
            lines.append(f'| {NAMES[code]} | {jn} ({apex + 1}, {max(ys):.1f}) | ' + ' | '.join(cells) + ' |')
    text = '\n'.join(lines) + '\n'
    if out: open(out, 'w').write(text)
    print(text)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
