"""On-shield frame advantage from the measured frame data (datkit movedata): how many frames the attacker is free before
(+) or after (-) the shielder can act, on a hard shield. Shieldstun = floor(0.45 x damage + 2) (ftCo_80092F2C with PlCo's
constants: 1.5 x damage x 0.3 + 2); hitlag freezes both fighters equally, so it cancels.
  ground move, hit on its first active frame: stun - (IASA - startup)   (the move's end after contact)
  aerial, best case (hit, then land at once, L-cancelled): stun - L-cancelled lag
Shield grab comes out on frame 7 for most of the cast (-7 or better is safe from it if he can jump away first: -4 with a
3-frame jumpsquat). A crossup lands behind the shield, where the grab can't reach.
    .venv/bin/python projects/geno/director/labs/shield_safety.py MOVEDATA [OUT.md]
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from cast_moves import load, attrs, metrics, NAMES

GROUND = ['jab1', 'ftilt', 'utilt', 'dtilt', 'dash_attack', 'fsmash', 'usmash', 'dsmash']
AERIAL = ['nair', 'fair', 'bair', 'uair', 'dair']
WHO = ['Ge', 'Fx', 'Fc', 'Ms', 'Sk', 'Ca']


def stun(d):
    return int(0.45 * d + 2)


def main(d, out=None):
    data, at = load(d), attrs()
    lines = ['# On-shield advantage (computed from measured frame data)', '',
             'Frames the attacker is free before (+) or after (-) the shielder can act, hard shield, fresh damage. '
             'Ground moves hit on their first active frame; aerials are the best case (land right after the hit, '
             'L-cancelled). Generated by `director/labs/shield_safety.py`.', '',
             '| move | ' + ' | '.join(NAMES[w] for w in WHO) + ' |', '|---|' + '---|' * len(WHO)]
    for mv in GROUND + AERIAL:
        cells = []
        for w in WHO:
            m = metrics(w, mv, data.get(w, {}).get(mv), at)
            if not m:
                cells.append('-'); continue
            s = stun(m['damage'])
            adv = s - m['l_cancel'] if mv in AERIAL else s - (m['total'] - m['startup'])
            cells.append(f"**{adv:+d}**" if w == 'Ge' else f'{adv:+d}')
        lines.append(f'| {mv} | ' + ' | '.join(cells) + ' |')
    text = '\n'.join(lines) + '\n'
    if out: open(out, 'w').write(text)
    print(text)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
